import type { Metadata } from "next";
import TopBar from "@/components/TopBar";
import { getServerSession } from "next-auth";
import { AuthOptions } from "next-auth";
import NextAuthProvider from "@/providers/NextAuthProviders";
import { authOptions } from "@/libs/authOptions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const nextAuthSession = await getServerSession(authOptions) 
  return (
    <html lang="en">
      <head>
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin=""/>
          <link href="https://fonts.googleapis.com/css2?family=Datatype:wght@100..900&family=Electrolize&family=Jura:wght@300..700&family=Major+Mono+Display&display=swap" rel="stylesheet"/>
      </head>
      <body>
          {children}
      </body>
    </html>
  );
}
