import type { Metadata } from "next";
import TopBar from "@/components/TopBar";
import { getServerSession } from "next-auth";
import { AuthOptions } from "next-auth";
import NextAuthProvider from "@/providers/NextAuthProviders";
import { authOptions } from "@/libs/authOptions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const nextAuthSession = await getServerSession(authOptions) 
  return (
      <>
          {children}
      </>
  );
}
